### ISSUE TITLE
Problems running example per the README

### ISSUE THREAD

**Issue by machawk1** [unt-libraries/py-wasapi-client#25]
I am using 94ad50407edec61417823db64846bbf0a65c970d of wasapi-client:
```
$ wasapi-client -v
Non-JSON response from https://partner.archive-it.org/wasapi/v1/webdata
2018-05-02 13:02:58,718 INFO wasapi_client requesting https://partner.archive-it.org/wasapi/v1/webdata
$ python3 --version
Python 3.6.5
```

After setting up my `~/.wasapi-client` with
```
[test]
username = myarchiveitusername
password = myarchiveitpassword
```
I attempt to download the WARCs for one crawl in my account using:
```wasapi-client --profile test --crawl 509053 --log out.log -p 1```

but am returned an error:
```py
Traceback (most recent call last):
  File "/usr/local/bin/wasapi-client", line 11, in <module>
    load_entry_point('py-wasapi-client==0.1', 'console_scripts', 'wasapi-client')()
  File "/usr/local/lib/python3.6/site-packages/py_wasapi_client-0.1-py3.6.egg/EGG-INFO/scripts/wasapi_client.py", line 604, in main
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```

Can you suggest on how to proceed to make this work?

**Comment by ldko** [comment]
Right now I am only getting 500 errors if I log into https://partner.archive-it.org/. @machawk1 are you able to log in to https://partner.archive-it.org/ currently?

**Comment by machawk1** [comment]
@ldko I get a 500 as well, both from my session that is already logged in and when starting a new session and providing credentials using Incognito.

**Comment by ldko** [comment]
@machawk1 It looks like there was an error on the Archive-It server side. It looks like it is working again. Could you try your attempt to download WARCs again and let me know if you get an error? I was able to run a similar command and download a WARC.

**Comment by ldko** [comment]
Oh, I just noticed this: [`Note that this may raise NotImplementedError on Unix platforms like Mac OS X where sem_getvalue() is not implemented.`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue.qsize). It looks like you may be encountering a platform specific issue. I will look at replacing the qsize call with something more portable. What OS are you using? I have run this on Ubuntu and Windows 10 I think only...

**Comment by machawk1** [comment]
@ldko I repeated the above command and got the same result. I am on macOS 10.13.4.

**Comment by machawk1** [comment]
That is very likely the issue. The below throws the same exception:
```py
from multiprocessing import Queue

q = Queue()
q.qsize()
```

```py
$ python3 testQ.py 
Traceback (most recent call last):
  File "testQ.py", line 4, in <module>
    q.qsize()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```

**Comment by ldko** [comment]
Thanks for testing that out. I have added a branch here: https://github.com/unt-libraries/py-wasapi-client/tree/fix-qsize-error. Would you mind trying that out?

**Comment by machawk1** [comment]
@ldko I pulled and rebased on that branch. All seems to be working as expected now. Thanks!

**Comment by ldko** [comment]
cool thanks for trying it out @machawk1 !
