### ISSUE TITLE
Considered releasing to pypi?

### ISSUE THREAD

**Issue by machawk1** [unt-libraries/py-wasapi-client#32]
Many Python developers use pip to install dependencies, which defaults to pulling modules from [PyPI](https://pypi.org/). This package (py-wasapi-client) does not appear to be available in PyPI. Are there any barriers or considerations from preventing this module as being available in PyPI?

**Comment by ldko** [comment]
@machawk1 thanks for bringing this up. For packages in our department we tend to deploy from Github master using `pip` and requirements files, so I often don't think about PyPI. We are generally happy to release code there though if people want it. I will get this on PyPI soon--there is no barrier.

**Comment by machawk1** [comment]
@ldko It would definitely be useful for other tools that hope to build on py-wasapi-client to have it available on PyPI. For example, one could specify the PyPI package name instead of the GitHub URI/branch in the derivative tool's requirements file.

I look forward to you getting it on there, as I hope to leverage the functionality of py-wasapi-client in some other Python tools.

**Comment by ldko** [comment]
@machawk1 py-wasapi-client is now on PyPI, thanks!

https://pypi.org/project/py-wasapi-client/
